name: release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  nfpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up nfpm
        uses: goreleaser/nfpm-action@v2
        with:
          version: latest

      - name: Build packages
        run: nfpm pkg -f packaging/nfpm.yaml -p deb -p rpm -p tar.gz -t dist/

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
